### PR TITLE
Convert Client::_fetch_target's lookup fn into a method

### PR DESCRIPTION
**Pull request by erickt**
This is a minor simplification of `Client::_fetch_target` to
factor out the interior lookup function in order to cut
out on a number of variables being passed in as arguments.

### CODE REVIEW

**Comment by heartsucker** [comment]
Boop-ing for rebase. (Looks good though. Will do a final check at the end.)

**Comment by erickt** [comment]
Rebased as well.

**Comment by erickt** [comment]
Boop-ing for a review :)

**Comment by heartsucker** [comment]
Yup, I’m on vacation so it might take a few :)

Von meinem iPhone gesendet

**Comment by erickt** [comment]
No problem! Thanks so much!

**Comment by heartsucker** [comment]
Poking for rebase.

**Comment by erickt** [comment]
It took a rather long while, but I finally rebased this patch!

**Review by heartsucker — APPROVED** [review]

**Pull request merged**
